### ISSUE TITLE
Exception in thread Thread-1:

### ISSUE THREAD

**Issue by Aristi35** [kochlisGit/ProphitBet-Soccer-Bets-Predictor#34]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Aristi\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Aristi\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Aristi\Documents\Dev\ProphitBet-Soccer-Bets-Predictor-main\gui\dialogs\league.py", line 120, in _store_league
    matches_df, league = self._league_repository.create_league(
  File "C:\Users\Aristi\Documents\Dev\ProphitBet-Soccer-Bets-Predictor-main\database\repositories\league.py", line 79, in create_league
    matches_df = MainLeagueAPI().download(league=league)
  File "C:\Users\Aristi\Documents\Dev\ProphitBet-Soccer-Bets-Predictor-main\database\network\footballdata\api.py", line 12, in download
    matches_df = self._download(league=league)
  File "C:\Users\Aristi\Documents\Dev\ProphitBet-Soccer-Bets-Predictor-main\database\network\footballdata\main.py", line 19, in _download
    return league_matches_dfs[0] if len(league_matches_dfs) == 1 else pd.concat(league_matches_dfs)
  File "C:\Users\Aristi\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Aristi\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\reshape\concat.py", line 347, in concat
    op = _Concatenator(
  File "C:\Users\Aristi\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\reshape\concat.py", line 404, in __init__
    raise ValueError("No objects to concatenate")

**Comment by Aristi35** [comment]
I'm install all requeriments, but i run program, when i want crearte league, show me this in console :c , any soluction ?

**Comment by arismelSoaint** [comment]
FIXED USING A VPN
