### ISSUE TITLE
Value Error numpy.ndarray size changed when starting from virtualenv in Python 3.9.11

### ISSUE THREAD

**Issue by supertipster** [kochlisGit/ProphitBet-Soccer-Bets-Predictor#4]
Hi Vasileios,

happy new year to you.

Great work so far but unfortenately ProphitBet will not start in my virtualenvironment. I use for this environment Python 3.9.11.
After starting main.py i get following error.
-------------------------------------------------------------------------------------------------------------------------------------------
(myenv_py_3_9) C:\Users\romai\Desktop\Soccer Database\ProphitBet>main.py
Traceback (most recent call last):
  File "C:\Users\romai\Desktop\Soccer Database\ProphitBet\main.py", line 1, in <module>
    from gui.main.window import MainWindow
  File "C:\Users\romai\Desktop\Soccer Database\ProphitBet\gui\main\window.py", line 11, in <module>
    from gui.dialogs.model import TrainNNCustomDialog, TrainNNAutoDialog, TrainRFDialog, EvaluationDialog, PredictionDialog, PredictionUpcomingDialog
  File "C:\Users\romai\Desktop\Soccer Database\ProphitBet\gui\dialogs\model.py", line 8, in <module>
    from fixtures.similarities.matching import TeamSimilarityMatching
  File "C:\Users\romai\Desktop\Soccer Database\ProphitBet\fixtures\similarities\matching.py", line 1, in <module>
    from py_stringmatching.similarity_measure.monge_elkan import MongeElkan
  File "C:\Users\romai\Desktop\pythonproject\myenv_py_3_9\lib\site-packages\py_stringmatching\__init__.py", line 16, in <module>
    from py_stringmatching.similarity_measure.generalized_jaccard import GeneralizedJaccard
  File "C:\Users\romai\Desktop\pythonproject\myenv_py_3_9\lib\site-packages\py_stringmatching\similarity_measure\generalized_jaccard.py", line 4, in <module>
    from py_stringmatching.similarity_measure.jaro import Jaro
  File "C:\Users\romai\Desktop\pythonproject\myenv_py_3_9\lib\site-packages\py_stringmatching\similarity_measure\jaro.py", line 5, in <module>
    from py_stringmatching.similarity_measure.cython.cython_jaro import jaro
  File "py_stringmatching/similarity_measure/cython/cython_jaro.pyx", line 2, in init py_stringmatching.similarity_measure.cython.cython_jaro
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
------------------------------------------------------------------------------------------------------------------------------------------------
Here is my list of installed package versions in the virtualenv.
-----------------------------------------------------------------------------------------------------------------------------------------------
(myenv_py_3_9) C:\Users\romai\Desktop\Soccer Database\ProphitBet>pip list
Package                      Version
---------------------------- ---------
absl-py                      1.3.0
alembic                      1.9.1
astunparse                   1.6.3
attrs                        22.2.0
autopage                     0.5.1
cachetools                   5.2.0
certifi                      2022.12.7
charset-normalizer           2.1.1
cliff                        4.1.0
cmaes                        0.9.0
cmd2                         2.4.2
colorama                     0.4.6
colorlog                     6.7.0
contourpy                    1.0.6
cycler                       0.11.0
flatbuffers                  22.12.6
fonttools                    4.38.0
gast                         0.4.0
google-auth                  2.15.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
greenlet                     2.0.1
grpcio                       1.51.1
h5py                         3.7.0
idna                         3.4
importlib-metadata           4.13.0
joblib                       1.2.0
keras                        2.11.0
kiwisolver                   1.4.4
libclang                     14.0.6
Mako                         1.2.4
Markdown                     3.4.1
MarkupSafe                   2.1.1
matplotlib                   3.6.2
matplotlip                   0.2
numpy                        1.20.3
oauthlib                     3.2.2
opt-einsum                   3.3.0
optuna                       3.0.5
packaging                    22.0
pandas                       1.5.2
pbr                          5.11.0
Pillow                       9.4.0
pip                          22.3.1
prettytable                  3.5.0
protobuf                     3.19.6
py-stringmatching            0.4.2
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pyparsing                    3.0.9
pyperclip                    1.8.2
pyreadline3                  3.4.1
python-dateutil              2.8.2
pytz                         2022.7
PyYAML                       6.0
requests                     2.28.1
requests-oauthlib            1.3.1
rsa                          4.9
scikit-learn                 1.2.0
scipy                        1.8.1
seaborn                      0.12.2
setuptools                   65.6.3
six                          1.16.0
SQLAlchemy                   1.4.45
stevedore                    4.1.1
tensorboard                  2.11.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.11.0
tensorflow-addons            0.19.0
tensorflow-estimator         2.11.0
tensorflow-intel             2.11.0
tensorflow-io-gcs-filesystem 0.29.0
termcolor                    2.1.1
threadpoolctl                3.1.0
tk                           0.1.0
tqdm                         4.64.1
typeguard                    2.13.3
typing_extensions            4.4.0
urllib3                      1.26.13
wcwidth                      0.2.5
Werkzeug                     2.2.2
wheel                        0.38.4
wrapt                        1.14.1
xgboost                      1.7.2
zipp                         3.11.0
--------------------------------------------------------------------------------------------------------------------------------------------------

Can you please help in this issue. It is a very interesting project an I'd like to be part of it.

Shoutouts from Germany

Romain

**Comment by kochlisGit** [comment]
Yeah ok, I see. It says:
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
There must be an incompatibility issue with the numpy library. Try deleting and re-installing a lower version of tensorflow (e.g. tensorflow 2.9 by using: pip uninstall tensorflow and then pip install tensorflow==2.9.1) and re-install py_stringmatching using –no-cache-dir flag (e.g. pip install py_stringmatching –no-cache-dir). If that doesn’t work, you should also downgrade the numpy and see if it works.

From: ***@***.***>
Sent: Monday, January 2, 2023 8:54 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [kochlisGit/ProphitBet-Soccer-Bets-Predictor] Value Error numpy.ndarray size changed when starting from virtualenv in Python 3.9.11 (Issue #4)


Hi Vasileios,

happy new year to you.

Great work so far but unfortenately ProphitBet will not start in my virtualenvironment. I use for this environment Python 3.9.11.
After starting main.py i get following error.
(myenv_py_3_9) C:\Users\romai\Desktop\Soccer Database\ProphitBet>main.py
Traceback (most recent call last):
File "C:\Users\romai\Desktop\Soccer Database\ProphitBet\main.py", line 1, in
from gui.main.window import MainWindow
File "C:\Users\romai\Desktop\Soccer Database\ProphitBet\gui\main\window.py", line 11, in
from gui.dialogs.model import TrainNNCustomDialog, TrainNNAutoDialog, TrainRFDialog, EvaluationDialog, PredictionDialog, PredictionUpcomingDialog
File "C:\Users\romai\Desktop\Soccer Database\ProphitBet\gui\dialogs\model.py", line 8, in
from fixtures.similarities.matching import TeamSimilarityMatching
File "C:\Users\romai\Desktop\Soccer Database\ProphitBet\fixtures\similarities\matching.py", line 1, in
from py_stringmatching.similarity_measure.monge_elkan import MongeElkan
File "C:\Users\romai\Desktop\pythonproject\myenv_py_3_9\lib\site-packages\py_stringmatching_init_.py", line 16, in
from py_stringmatching.similarity_measure.generalized_jaccard import GeneralizedJaccard
File "C:\Users\romai\Desktop\pythonproject\myenv_py_3_9\lib\site-packages\py_stringmatching\similarity_measure\generalized_jaccard.py", line 4, in
from py_stringmatching.similarity_measure.jaro import Jaro
File "C:\Users\romai\Desktop\pythonproject\myenv_py_3_9\lib\site-packages\py_stringmatching\similarity_measure\jaro.py", line 5, in
from py_stringmatching.similarity_measure.cython.cython_jaro import jaro
File "py_stringmatching/similarity_measure/cython/cython_jaro.pyx", line 2, in init py_stringmatching.similarity_measure.cython.cython_jaro
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
Here is my list of installed package versions in the virtualenv.

(myenv_py_3_9) C:\Users\romai\Desktop\Soccer Database\ProphitBet>pip list
Package Version

absl-py 1.3.0
alembic 1.9.1
astunparse 1.6.3
attrs 22.2.0
autopage 0.5.1
cachetools 5.2.0
certifi 2022.12.7
charset-normalizer 2.1.1
cliff 4.1.0
cmaes 0.9.0
cmd2 2.4.2
colorama 0.4.6
colorlog 6.7.0
contourpy 1.0.6
cycler 0.11.0
flatbuffers 22.12.6
fonttools 4.38.0
gast 0.4.0
google-auth 2.15.0
google-auth-oauthlib 0.4.6
google-pasta 0.2.0
greenlet 2.0.1
grpcio 1.51.1
h5py 3.7.0
idna 3.4
importlib-metadata 4.13.0
joblib 1.2.0
keras 2.11.0
kiwisolver 1.4.4
libclang 14.0.6
Mako 1.2.4
Markdown 3.4.1
MarkupSafe 2.1.1
matplotlib 3.6.2
matplotlip 0.2
numpy 1.20.3
oauthlib 3.2.2
opt-einsum 3.3.0
optuna 3.0.5
packaging 22.0
pandas 1.5.2
pbr 5.11.0
Pillow 9.4.0
pip 22.3.1
prettytable 3.5.0
protobuf 3.19.6
py-stringmatching 0.4.2
pyasn1 0.4.8
pyasn1-modules 0.2.8
pyparsing 3.0.9
pyperclip 1.8.2
pyreadline3 3.4.1
python-dateutil 2.8.2
pytz 2022.7
PyYAML 6.0
requests 2.28.1
requests-oauthlib 1.3.1
rsa 4.9
scikit-learn 1.2.0
scipy 1.8.1
seaborn 0.12.2
setuptools 65.6.3
six 1.16.0
SQLAlchemy 1.4.45
stevedore 4.1.1
tensorboard 2.11.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit 1.8.1
tensorflow 2.11.0
tensorflow-addons 0.19.0
tensorflow-estimator 2.11.0
tensorflow-intel 2.11.0
tensorflow-io-gcs-filesystem 0.29.0
termcolor 2.1.1
threadpoolctl 3.1.0
tk 0.1.0
tqdm 4.64.1
typeguard 2.13.3
typing_extensions 4.4.0
urllib3 1.26.13
wcwidth 0.2.5
Werkzeug 2.2.2
wheel 0.38.4
wrapt 1.14.1
xgboost 1.7.2
zipp 3.11.0

Can you please help in this issue. It is a very interesting project an I'd like to be part of it.

Shoutouts from Germany

Romain

**Comment by supertipster** [comment]
Hi Vasileios,

thank you for your quick response.
I have made a new virtualenvironment with Python 3.9.1 and older package installs (each the first of 2021 if possible). But unfortenately I got the same package error like yesterday with another size that was given (yesterday 88 - today 80 - expected was 96)

Is it possible to get an requirements.txt for the packages from you? Following I've attached my pip list of my virtualenvironment an the error output.

I try to execute ProphiBet on an laptop with Windows 11 and an simple dedicated GeForce MX250 GPU.

Thanks for supporting me.

Romain

`(myvenv_py_3_9_1) C:\Users\romai\Desktop\Soccer Database\ProphitBet>main.py
2023-01-03 18:38:08.791730: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-01-03 18:38:08.791894: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "C:\Users\romai\Desktop\Soccer Database\ProphitBet\main.py", line 1, in <module>
    from gui.main.window import MainWindow
  File "C:\Users\romai\Desktop\Soccer Database\ProphitBet\gui\main\window.py", line 11, in <module>
    from gui.dialogs.model import TrainNNCustomDialog, TrainNNAutoDialog, TrainRFDialog, EvaluationDialog, PredictionDialog, PredictionUpcomingDialog
  File "C:\Users\romai\Desktop\Soccer Database\ProphitBet\gui\dialogs\model.py", line 8, in <module>
    from fixtures.similarities.matching import TeamSimilarityMatching
  File "C:\Users\romai\Desktop\Soccer Database\ProphitBet\fixtures\similarities\matching.py", line 1, in <module>
    from py_stringmatching.similarity_measure.monge_elkan import MongeElkan
  File "C:\Users\romai\Desktop\pythonproject\myvenv_py_3_9_1\lib\site-packages\py_stringmatching\__init__.py", line 16, in <module>
    from py_stringmatching.similarity_measure.generalized_jaccard import GeneralizedJaccard
  File "C:\Users\romai\Desktop\pythonproject\myvenv_py_3_9_1\lib\site-packages\py_stringmatching\similarity_measure\generalized_jaccard.py", line 4, in <module>
    from py_stringmatching.similarity_measure.jaro import Jaro
  File "C:\Users\romai\Desktop\pythonproject\myvenv_py_3_9_1\lib\site-packages\py_stringmatching\similarity_measure\jaro.py", line 5, in <module>
    from py_stringmatching.similarity_measure.cython.cython_jaro import jaro
  File "py_stringmatching/similarity_measure/cython/cython_jaro.pyx", line 2, in init py_stringmatching.similarity_measure.cython.cython_jaro
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject

(myvenv_py_3_9_1) C:\Users\romai\Desktop\Soccer Database\ProphitBet>pip list
Package                 Version
----------------------- -------------------
absl-py                 0.15.0
alembic                 1.9.1
astunparse              1.6.3
attrs                   22.2.0
autopage                0.5.1
cachetools              5.2.0
certifi                 2022.12.7
charset-normalizer      2.1.1
cliff                   4.1.0
cmaes                   0.9.0
cmd2                    2.4.2
colorama                0.4.6
colorlog                6.7.0
contourpy               1.0.6
cycler                  0.11.0
flatbuffers             1.12
fonttools               4.38.0
gast                    0.4.0
google-auth             2.15.0
google-auth-oauthlib    0.4.6
google-pasta            0.2.0
greenlet                2.0.1
grpcio                  1.34.1
h5py                    3.1.0
idna                    3.4
importlib-metadata      6.0.0
joblib                  1.2.0
keras-nightly           2.5.0.dev2021032900
Keras-Preprocessing     1.1.2
kiwisolver              1.4.4
Mako                    1.2.4
Markdown                3.4.1
MarkupSafe              2.1.1
matplotlib              3.6.2
matplotlip              0.2
numpy                   1.19.5
oauthlib                3.2.2
opt-einsum              3.3.0
optuna                  2.4.0
packaging               22.0
pandas                  1.2.0
pbr                     5.11.0
Pillow                  9.4.0
pip                     22.3.1
prettytable             3.5.0
protobuf                3.20.3
py-stringmatching       0.4.2
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pyparsing               3.0.9
pyperclip               1.8.2
pyreadline3             3.4.1
python-dateutil         2.8.2
pytz                    2022.7
PyYAML                  6.0
requests                2.28.1
requests-oauthlib       1.3.1
rsa                     4.9
scikit-learn            0.24.1
scipy                   1.9.3
seaborn                 0.11.2
setuptools              65.6.3
six                     1.15.0
SQLAlchemy              1.4.45
stevedore               4.1.1
tensorboard             2.11.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
tensorflow              2.5.0
tensorflow-addons       0.13.0
tensorflow-estimator    2.5.0
termcolor               1.1.0
threadpoolctl           3.1.0
tk                      0.1.0
tqdm                    4.64.1
typeguard               2.13.3
typing-extensions       3.7.4.3
urllib3                 1.26.13
wcwidth                 0.2.5
Werkzeug                2.2.2
wheel                   0.38.4
wrapt                   1.12.1
xgboost                 1.3.3
zipp                    3.11.0`
