### ISSUE TITLE
The program shows Blank screen

### ISSUE THREAD

**Issue by Takudzwa413** [kochlisGit/ProphitBet-Soccer-Bets-Predictor#41]
I ran the program and it shows blank screen help

<img width="1280" alt="Screenshot 2023-10-15 at 13 49 32" src="https://github.com/kochlisGit/ProphitBet-Soccer-Bets-Predictor/assets/61545682/a02be014-c2e3-4544-90f5-75d4487593c4">

**Comment by ZockerFox** [comment]
Thats correct. First you have to Create a League (Application - Create League). Then you will see the last matches of the league in the window.

**Comment by Quasibzaar** [comment]
I get this far, and i create a new league, how long should it take to create? 60.min+ now, but nothing happening.

**Comment by KnightRider37** [comment]
It's fast to create a new league. Make sure you didn't change anything in the csv file where you have the leagues. try creating some leagues that are already in the file at first.

**Comment by Takudzwa413** [comment]
Okay i got to work, but have any of you managed to train a module for predictions ?? its taking hours loading and im giving up along the way

**Comment by ZockerFox** [comment]
Hi, it takes about 5 to 10 minutes depending on the training. Maybe there are some error messages or exceptions in the terminal window/windows cmd window you should check.

**Comment by Quasibzaar** [comment]
Everything works fine on startup, but when I push the create-btn i get this message (I haven't changed anything in the csv-files):
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/frodeeriksen/Downloads/ProphitBet-Soccer-Bets-Predictor-main/gui/dialogs/league.py", line 115, in _store_league
    matches_df, league = self._league_repository.create_league(
  File "/Users/frodeeriksen/Downloads/ProphitBet-Soccer-Bets-Predictor-main/database/repositories/league.py", line 77, in create_league
    matches_df = MainLeagueAPI().download(league=league)
  File "/Users/frodeeriksen/Downloads/ProphitBet-Soccer-Bets-Predictor-main/database/network/footballdata/api.py", line 9, in download
    matches_df = self._download(league=league)
  File "/Users/frodeeriksen/Downloads/ProphitBet-Soccer-Bets-Predictor-main/database/network/footballdata/main.py", line 19, in _download
    return league_matches_dfs[0] if len(league_matches_dfs) == 1 else pd.concat(league_matches_dfs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 347, in concat
    op = _Concatenator(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 404, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

**Comment by ZockerFox** [comment]
1. Which league you wanted to create?

2. Replace the exception handler in file database/network/footballdata/main.py in line 17/18 with a more detailed output:

```
            except FileNotFoundError:
                   print("File not found.")
            except pd.errors.EmptyDataError:
                   print("No data")
            except pd.errors.ParserError:
                   print("Parse error")
            except pd.errors.AbstractMethodError:
                   print("Abs other exception")
            except pd.errors.AccessorRegistrationWarning:
                   print("Reg other exception")
            except pd.errors.DtypeWarning:
                   print("Dtype other exception")
            except pd.errors.DuplicateLabelError:
                   print("Label other exception")
            except pd.errors.IntCastingNaNError:
                   print("Int other exception")
            except pd.errors.InvalidIndexError:
                   print("Index other exception")
            except pd.errors.MergeError:
                   print("Merge other exception")
            except pd.errors.NullFrequencyError:
                   print("Null other exception")
            except pd.errors.NumbaUtilError:
                   print("Numba other exception")
            except pd.errors.OptionError:
                   print("Option other exception")
            except pd.errors.OutOfBoundsDatetime:
                   print("Date other exception")
            except pd.errors.OutOfBoundsTimedelta:
                   print("Time other exception")
            except pd.errors.ParserWarning:
                   print("Warn other exception")
            except pd.errors.PerformanceWarning:
                   print("Perf other exception")
            except pd.errors.UnsortedIndexError:
                   print("Unsorted other exception")
            except pd.errors.UnsupportedFunctionCall:
                   print("unsoop other exception")


````

**Comment by sushii2** [comment]
When I click on create league, nothing shows up just a blank screen.
Can someone suggest something
![image](https://github.com/kochlisGit/ProphitBet-Soccer-Bets-Predictor/assets/34906191/5b727d9e-0647-44ee-93c9-9fd50722b23c)
