### ISSUE TITLE
PANDA REQUEST ERROR

### ISSUE THREAD

**Issue by Jonatang12** [kochlisGit/ProphitBet-Soccer-Bets-Predictor#56]
Hello, every time I go to start the application this appears and it doesn't let me open the application, both with the cmd and with the visual code I get the same error
Traceback (most recent call last):
   File "C:\Users\jonatan\Desktop\ProphitBet-Soccer-Bets-Predictor-main - copy\main.py", line 1, in <module>
     from database.repositories.league import LeagueRepository
   File "C:\Users\jonatan\Desktop\ProphitBet-Soccer-Bets-Predictor-main - copy\database\repositories\league.py", line 4, in <module>
     import panda as pd
   File "C:\Users\jonatan\AppData\Roaming\Python\Python311\site-packages\panda\__init__.py", line 1, in <module>
     from request import PandaRequest
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'request'
this is the error that appears to me
![Screenshot_2](https://github.com/kochlisGit/ProphitBet-Soccer-Bets-Predictor/assets/150976750/8f7c3dd4-eb5d-4db9-918d-80ba605aa2b3)

**Comment by jideswaggs** [comment]
What python version are you running
