### ISSUE TITLE
ERROR LEAGUE

### ISSUE THREAD

**Issue by Papito8z** [kochlisGit/ProphitBet-Soccer-Bets-Predictor#6]
I have a problem when I run the file with Visual Code, the Prophitbet application opens correctly but in the league menu to create a league a white window opens. When I go back to the Visual Studio Code code, a file error appears on the league : 
PS C:\Users\Liamine> & C:/Users/Liamine/AppData/Local/Microsoft/WindowsApps/python3.9.exe c:/Users/Liamine/Downloads/ProphitBet-Soccer-Bets-Predictor-main/main.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1892, in __call__       
    return self.func(*args)
  File "c:\Users\Liamine\Downloads\ProphitBet-Soccer-Bets-Predictor-main\gui\main\application.py", line 159, in _create_league
    self._open_league_name, self._open_league, self._matches_df = CreateLeagueDialog(
  File "c:\Users\Liamine\Downloads\ProphitBet-Soccer-Bets-Predictor-main\gui\dialogs\league.py", line 16, in __init__
    self._all_leagues = league_repository.get_all_available_leagues()
  File "c:\Users\Liamine\Downloads\ProphitBet-Soccer-Bets-Predictor-main\database\repositories\league.py", line 20, in get_all_available_leagues
    with open(file=self._available_leagues_filepath, mode='r', encoding='utf=8') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'database/storage/leagues/available_leagues.csv'

can you help e ?

**Comment by kochlisGit** [comment]
Try not to run it with visual studio code. Instead, you can double click on main.py (on windows) or open a cmd/terminal inside the folder and type: python main.py (windows) or python3 main.py on Linux.

From: ***@***.***>
Sent: Sunday, January 29, 2023 2:49 AM
To: ***@***.***>
Cc: ***@***.***>
Subject: [kochlisGit/ProphitBet-Soccer-Bets-Predictor] ERROR LEAGUE (Issue #6)


I have a problem when I run the file with Visual Code, the Prophitbet application opens correctly but in the league menu to create a league a white window opens. When I go back to the Visual Studio Code code, a file error appears on the league :
PS C:\Users\Liamine> & C:/Users/Liamine/AppData/Local/Microsoft/WindowsApps/python3.9.exe c:/Users/Liamine/Downloads/ProphitBet-Soccer-Bets-Predictor-main/main.py
Exception in Tkinter callback
Traceback (most recent call last):
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\tkinter_init_.py", line 1892, in call
return self.func(*args)
File "c:\Users\Liamine\Downloads\ProphitBet-Soccer-Bets-Predictor-main\gui\main\application.py", line 159, in _create_league
self._open_league_name, self._open_league, self._matches_df = CreateLeagueDialog(
File "c:\Users\Liamine\Downloads\ProphitBet-Soccer-Bets-Predictor-main\gui\dialogs\league.py", line 16, in init
self._all_leagues = league_repository.get_all_available_leagues()
File "c:\Users\Liamine\Downloads\ProphitBet-Soccer-Bets-Predictor-main\database\repositories\league.py", line 20, in get_all_available_leagues
with open(file=self._available_leagues_filepath, mode='r', encoding='utf=8') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'database/storage/leagues/available_leagues.csv'

can you help e ?

**Comment by Papito8z** [comment]
Thank you for your quick response. I also tried opening the main.py by double clicking it, the command opens a black screen, lines of code also appear, then an error message appears: permission error win error 5: access denied: 'database'.

I have ensured that I have all rights and access by checking the properties of the files, and using the icacls command, and I have full control over everything. I don't understand this very much... 

thank you

**Comment by kochlisGit** [comment]
Do you have windows or Linux?

**Comment by Papito8z** [comment]
I have windows . Thanks

**Comment by kochlisGit** [comment]
Try to re-download the repository

**Comment by Papito8z** [comment]
I downloaded again but it still does not work … the prophit bet application opens correctly but I cannot create a league.  I still have the same error message :((((

**Comment by kochlisGit** [comment]
Ok I see, it probably has something to do with your account rights. Are you an administrator on your computer?

**Comment by Papito8z** [comment]
I still can't run the file with python. I can't manage with visual code . I have authorized all access, I am the administrator. Do you have a miracle solution for me? thanks for your help

**Comment by kochlisGit** [comment]
Can you try to test it on another computer?  Another laptop maybe? Maybe it’s the application’s fault. Otherwise, for some weird reason, your computer prevents you from running python.

**Comment by Papito8z** [comment]
I uninstalled everything and reinstalled it all and now it works, thank you for your help and answers

**Comment by Papito8z** [comment]
Hi sorry again When i lauch the fixture i have this error :  Parsing Error: Failed to parse fixture table, because date "Feb
04 ~" was not found. Perhaps the selected date is incorrect or
the HTML of Footystats code has changed

**Comment by kochlisGit** [comment]
Yeah. Are you sure feb 04 date has a fixture? Did you check it on footystats.org?

**Comment by kochlisGit** [comment]
Does it happen on that league only on that league or others as well?

**Comment by Papito8z** [comment]
I test only in this test ! However i évaluate my model on 200 . I have 84%
of accuary INCREDIBLE good joob man

**Comment by Papito8z** [comment]
What are the best tuning parameters for your models? Thank you for your work.

**Comment by TYRANTHOSAURUS** [comment]
It happens on all leagues, i had it multiple times.

But when it succeed's it also gives invalid rows without odds if odds aren't there yet which cannot be removed unless you manually fill in fake odds.

Would be great to be able to remove incorrect rows

**Comment by Papito8z** [comment]
What is your best model for each league? What is your highest accuracy?"
