### ISSUE TITLE
Can't Create League

### ISSUE THREAD

**Issue by LucasWedel** [kochlisGit/ProphitBet-Soccer-Bets-Predictor#63]
I am getting this error when I'm trying to create any league. Tried with different versions of python and different versions of the libraries, but keeps happening:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py", line 12660, in _reindex_for_setitem
    reindexed_value = value.reindex(index)._values
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\series.py", line 5133, in reindex
    return super().reindex(
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\generic.py", line 5604, in reindex
    return self._reindex_axes(
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\generic.py", line 5627, in _reindex_axes
    new_index, indexer = ax.reindex(
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexes\base.py", line 4430, in reindex
    target = self._wrap_reindex_result(target, indexer, preserve_names)
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexes\multi.py", line 2717, in _wrap_reindex_result
    target = MultiIndex.from_tuples(target)
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexes\multi.py", line 222, in new_meth
    return meth(self_or_cls, *args, **kwargs)
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexes\multi.py", line 617, in from_tuples
    arrays = list(lib.tuples_to_object_array(tuples).T)
  File "lib.pyx", line 3029, in pandas._libs.lib.tuples_to_object_array
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long long'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\lucas\OneDrive\Documents\UNI Software\Prophitbet\ProphitBet-Soccer-Bets-Predictor\gui\task.py", line 35, in _submit_task
    self._result = self._task(*self._args)
  File "c:\Users\lucas\OneDrive\Documents\UNI Software\Prophitbet\ProphitBet-Soccer-Bets-Predictor\database\repositories\league.py", line 77, in create_league
    df = self._download_league_data(league_config=league_config, year_start=league_config.league.year_start)
  File "c:\Users\lucas\OneDrive\Documents\UNI Software\Prophitbet\ProphitBet-Soccer-Bets-Predictor\database\repositories\league.py", line 69, in _download_league_data
    df = stats_engine.compute_statistics(matches_df=df, features=league_config.features)
  File "c:\Users\lucas\OneDrive\Documents\UNI Software\Prophitbet\ProphitBet-Soccer-Bets-Predictor\preprocessing\statistics.py", line 132, in compute_statistics
    self._statistic_features[col](matches_df=matches_df)
  File "c:\Users\lucas\OneDrive\Documents\UNI Software\Prophitbet\ProphitBet-Soccer-Bets-Predictor\preprocessing\statistics.py", line 36, in compute_home_wins
    matches_df['HW'] = self._compute_last_results(matches_df=matches_df, team_column='Home Team', result='H')
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._set_item(key, value)
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py", line 4512, in _set_item
    value, refs = self._sanitize_column(value)
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py", line 5250, in _sanitize_column
    return _reindex_for_setitem(value, self.index)
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py", line 12667, in _reindex_for_setitem
    raise TypeError(
TypeError: incompatible index of inserted column with frame index

**Comment by kochlisGit** [comment]
Can you check the pandas version? (open command line (cmd) and type "`pip show pandas`")

**Comment by betninja1** [comment]
cant create league either
yesterday was working fine , i get this error

<urlopen error [Errno 11002] getaddrinfo failed>
Warning: Failed to download file: https://www.football-data.co.uk/mmz4281/1617/F1.csv from league: France: Ligue-1, Year = 2016
<urlopen error [Errno 11002] getaddrinfo failed>
Warning: Failed to download file: https://www.football-data.co.uk/mmz4281/1718/F1.csv from league: France: Ligue-1, Year = 2017
<urlopen error [Errno 11002] getaddrinfo failed>
Warning: Failed to download file: https://www.football-data.co.uk/mmz4281/1819/F1.csv from league: France: Ligue-1, Year = 2018
<urlopen error [Errno 11002] getaddrinfo failed>
Warning: Failed to download file: https://www.football-data.co.uk/mmz4281/1920/F1.csv from league: France: Ligue-1, Year = 2019
<urlopen error [Errno 11002] getaddrinfo failed>
Warning: Failed to download file: https://www.football-data.co.uk/mmz4281/2021/F1.csv from league: France: Ligue-1, Year = 2020
<urlopen error [Errno 11002] getaddrinfo failed>
Warning: Failed to download file: https://www.football-data.co.uk/mmz4281/2122/F1.csv from league: France: Ligue-1, Year = 2021
<urlopen error [Errno 11002] getaddrinfo failed>
Warning: Failed to download file: https://www.football-data.co.uk/mmz4281/2223/F1.csv from league: France: Ligue-1, Year = 2022
<urlopen error [Errno 11002] getaddrinfo failed>
Warning: Failed to download file: https://www.football-data.co.uk/mmz4281/2324/F1.csv from league: France: Ligue-1, Year = 2023

**Comment by kochlisGit** [comment]
This means that either your DNS system is not working correctly, or you have to use a proxy on your network and it isn't defined correctly.
