### ISSUE TITLE
Issue when clicking the create league

### ISSUE THREAD

**Issue by kennyyim** [kochlisGit/ProphitBet-Soccer-Bets-Predictor#67]
When i run the main.py, everything is fine. But When i clicked create league button after i selected some options from the menu, it shows the exception below and the progress bar keeps loading

below is the exception i get from the terminal:
  warnings.warn(
Exception in thread Thread-1 (_submit_task):
Traceback (most recent call last):
  File "C:\Users\kenny\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 12660, in _reindex_for_setitem
    reindexed_value = value.reindex(index)._values
  File "C:\Users\kenny\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\series.py", line 5133, in reindex
    return super().reindex(
  File "C:\Users\kenny\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py", line 5604, in reindex
    return self._reindex_axes(
  File "C:\Users\kenny\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py", line 5627, in _reindex_axes    
    new_index, indexer = ax.reindex(
  File "C:\Users\kenny\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 4430, in reindex     
    target = self._wrap_reindex_result(target, indexer, preserve_names)
  File "C:\Users\kenny\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\multi.py", line 2717, in _wrap_reindex_result
    target = MultiIndex.from_tuples(target)
  File "C:\Users\kenny\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\multi.py", line 222, in new_meth    
    return meth(self_or_cls, *args, **kwargs)
  File "C:\Users\kenny\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\multi.py", line 617, in from_tuples 
    arrays = list(lib.tuples_to_object_array(tuples).T)
  File "lib.pyx", line 3029, in pandas._libs.lib.tuples_to_object_array
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long long'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\kenny\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\kenny\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\kenny\personal study\ProphitBet-Soccer-Bets-Predictor-main\gui\task.py", line 35, in _submit_task
    self._result = self._task(*self._args)
  File "c:\Users\kenny\personal study\ProphitBet-Soccer-Bets-Predictor-main\database\repositories\league.py", line 77, in create_league  
    df = self._download_league_data(league_config=league_config, year_start=league_config.league.year_start)
  File "c:\Users\kenny\personal study\ProphitBet-Soccer-Bets-Predictor-main\database\repositories\league.py", line 69, in _download_league_data
    df = stats_engine.compute_statistics(matches_df=df, features=league_config.features)
  File "c:\Users\kenny\personal study\ProphitBet-Soccer-Bets-Predictor-main\preprocessing\statistics.py", line 132, in compute_statistics    self._statistic_features[col](matches_df=matches_df)
  File "c:\Users\kenny\personal study\ProphitBet-Soccer-Bets-Predictor-main\preprocessing\statistics.py", line 36, in compute_home_wins  
    matches_df['HW'] = self._compute_last_results(matches_df=matches_df, team_column='Home Team', result='H')
  File "C:\Users\kenny\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__        
    self._set_item(key, value)
  File "C:\Users\kenny\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 4512, in _set_item
    value, refs = self._sanitize_column(value)
  File "C:\Users\kenny\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 5250, in _sanitize_column   
    return _reindex_for_setitem(value, self.index)
  File "C:\Users\kenny\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 12667, in _reindex_for_setitem
    raise TypeError(
TypeError: incompatible index of inserted column with frame index

**Comment by Lakasitos2013** [comment]
I get the same error, no matter what version of pandas I install.

Have you managed to fix it?
