### ISSUE TITLE
Create League

### ISSUE THREAD

**Issue by yrevich99** [kochlisGit/ProphitBet-Soccer-Bets-Predictor#75]
Exception in thread Thread-1 (_submit_task):
Traceback (most recent call last):
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\frame.py", line 12674, in _reindex_for_setitem
    reindexed_value = value.reindex(index)._values
                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\series.py", line 5144, in reindex
    return super().reindex(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\generic.py", line 5607, in reindex
    return self._reindex_axes(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\generic.py", line 5630, in _reindex_axes
    new_index, indexer = ax.reindex(
                         ^^^^^^^^^^^
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexes\base.py", line 4433, in reindex
    target = self._wrap_reindex_result(target, indexer, preserve_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexes\multi.py", line 2717, in _wrap_reindex_result
    target = MultiIndex.from_tuples(target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexes\multi.py", line 222, in new_meth
    return meth(self_or_cls, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexes\multi.py", line 617, in from_tuples
    arrays = list(lib.tuples_to_object_array(tuples).T)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 3029, in pandas._libs.lib.tuples_to_object_array
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long long'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "d:\Downloads\ProphitBet-Soccer-Bets-Predictor-main\ProphitBet-Soccer-Bets-Predictor-main\gui\task.py", line 35, in _submit_task
    self._result = self._task(*self._args)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Downloads\ProphitBet-Soccer-Bets-Predictor-main\ProphitBet-Soccer-Bets-Predictor-main\database\repositories\league.py", line 77, in create_league
    df = self._download_league_data(league_config=league_config, year_start=league_config.league.year_start)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Downloads\ProphitBet-Soccer-Bets-Predictor-main\ProphitBet-Soccer-Bets-Predictor-main\database\repositories\league.py", line 69, in _download_league_data
    df = stats_engine.compute_statistics(matches_df=df, features=league_config.features)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Downloads\ProphitBet-Soccer-Bets-Predictor-main\ProphitBet-Soccer-Bets-Predictor-main\preprocessing\statistics.py", line 133, in compute_statistics
    self._statistic_features[col](matches_df=matches_df)
  File "d:\Downloads\ProphitBet-Soccer-Bets-Predictor-main\ProphitBet-Soccer-Bets-Predictor-main\preprocessing\statistics.py", line 36, in compute_home_wins
    matches_df['HW'] = self._compute_last_results(matches_df=matches_df, team_column='Home Team', result='H')
    ~~~~~~~~~~^^^^^^
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._set_item(key, value)
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\frame.py", line 4512, in _set_item
    value, refs = self._sanitize_column(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\frame.py", line 5250, in _sanitize_column
    return _reindex_for_setitem(value, self.index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\frame.py", line 12681, in _reindex_for_setitem
    raise TypeError(
TypeError: incompatible index of inserted column with frame index

**Comment by kochlisGit** [comment]
ok, what is your pandas version and python version? Open a cmd (command line) and type:

- `python --version` for the python version
- `pip show pandas` for the pandas version

Make sure they have the same version as the **requirements.txt** file on the project directory (or you can view it here: [https://github.com/kochlisGit/ProphitBet-Soccer-Bets-Predictor/blob/main/requirements.txt](https://github.com/kochlisGit/ProphitBet-Soccer-Bets-Predictor/blob/main/requirements.txt)
